version: 1.0.{build}
environment:
  REACT_APP_API_URL: http://localhost:3333
  NODEJS_VERSION: 18.16.1
install:
  - ps: Install-Product node $env:NODEJS_VERSION
  - ps: npm ci
build: off
test_script:
  - ps: npm run test
on_success:
  - sh: |
      curl -Os https://uploader.codecov.io/latest/linux/codecov

      chmod +x codecov
      ./codecov
